---
title: "Index file for the qcmetrics package vignette"
author: 
- name: Laurent Gatto
  affiliation: Computational Proteomics Unit, Cambridge, UK
package: qcmetrics
abstract: >
  The `r BiocStyle::Biocpkg("qcmetrics")` package is a framework that
  provides simple data containers for quality metrics and support for
  automatic report generation. This document briefly illustrates the
  core data structures and then demonstrates the generation and
  automation of quality control reports for microarray and proteomics
  data.  
output:
  BiocStyle::html_document:
    toc_float: true
vignette: >
  %\VignetteIndexEntry{Index file for the qcmetrics package vignette}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteKeywords{Bioinformatics, proteomics, genomics, transcriptomics, mass-spectrometry, Quality control, reporting}
  %\VignetteEncoding{UTF-8}
---

```{r env, echo=FALSE}
suppressPackageStartupMessages(library("BiocStyle"))
```

The full vignette is available in pdf format on the 
`r Biocpkg("qcmetrics")` Bioconductor landing page at 

  http://www.bioconductor.org/packages/devel/bioc/vignettes/qcmetrics/inst/doc/qcmetrics.pdf

# Session information

```{r si, echo=FALSE}
print(sessionInfo(), locale = FALSE)
```
